enum ScreenName {
    WELCOME = 'WELCOME',
    NAV_BAR = "NAVBAR",

    HOME = "HOME",
    CHAT = "CHAT",
    CREATE_CLASS = "CREATECLASS",
    PERSONAL_SCHEDULE = "PERSONALSCHEDULE",
    ACCOUNT = "ACCOUNT",

    MESSAGE = "MESSAGE",
    PROFILE = "PROFILE",
    SCANNER = "SCANNER",

    CLASS_LIST = "CLASSLIST",
    DETAIL_CLASS = "DETAILCLASS",
    RATING = "RATING",

    ATTENDANCE_HISTORY = "ATTENDANCEHISTORY",
    ATTENDED_FOR_LEARNER = "ATTENDEDFORLEARNER",
    ATTENDED_FOR_TUTOR = "ATTENDEDFORTUTOR",

    CV_LIST = "CVLIST",
    CV = "CV",
    INPUT_CV = "INPUTCV",

    OTP = "OTP",
    LOGIN = "LOGIN",
    REGISTER_STEP_1 = "REGISTERSTEP1",
    REGISTER_STEP_2 = "REGISTERSTEP2",

    CHANGE_PASSWORD = "CHANGEPASSWORD",

    // Admin
    HOME_ADMIN = "HOMEADMIN",
    CLASS_MANAGER = "CLASSMANAGER",
    GENERAL_MANAGER = "GENERALMANAGER",
    USER_MANAGER = "USERMANAGER",
    USER_REPORT_LIST = "USERREPORTLIST",
    USER_REPORT_DETAIL = "USERREPORTDETAIL",

    REPORT_CLASS = "REPORTCLASS",

    APP_INFO_MANAGEMENT = "APPINFOMANAGEMENT",
    PERMISSION_MANAGEMENT = "PERMISSIONSMANAGEMENT",
    CLASS_MANAGEMENT = "CLASSMANAGEMENT",
    APPROVE_CLASS = "APPROVECLASS",
    USER_MANAGEMENT = "USERMANAGEMENT",
    GENERAL_MANAGEMENT = "GENERALMANAGEMENT",

    CV_APPROVAL = "CVAPPROVAL",
    CLASS_APPROVAL = "CLASSAPPROVAL",

    SETTING_INFO_PERSONAL = "SETTINGINFORMATIONPERSONAL",
    SETTING_PERSONAL_CV = "SETTINGPERSONALCV",
    SETTING_PERSONAL_CLASSES = "SETTINGPERSONALCLASSES",
    SETTING_PERSONAL_RATINGS = "SETTINGPERSONALRATINGS",

    CREATE_ACCOUNT_ADMIN = "CREATEACCOUNTADMIN",
}

export default ScreenName;